#!/bin/bash
if [ -n "$SSH_TTY" ]; then
    nc -q0 127.0.0.1 9999
else
    if command -v pbcopy &>/dev/null; then
        pbcopy
    elif command -v wl-copy &>/dev/null; then
        wl-copy
    elif command -v xclip &>/dev/null; then
        xclip -selection clipboard
    fi
fi
